package enums;

public enum ConfigProperties {
    URLGOOGLE,
    URLORANGEHRMLOGINPAGE,
    USERNAME,
    PASSWORD,
    PASSWORDINVALID,
    INVALIDCREDENTIALSERRORMESSAGE,
    BROWSERS
}
